
INSERT INTO engineering_college (college_name, city, type, affiliation) VALUES
('Indian Institute of Technology Gandhinagar', 'Gandhinagar', 'National', 'IIT'),
('Sardar Vallabhbhai National Institute of Technology Surat', 'Surat', 'National', 'NIT'),
('Dhirubhai Ambani Institute of Information and Communication Technology', 'Gandhinagar', 'Private', 'GTU'),
('Indian Institute of Information Technology Vadodara', 'Vadodara', 'National', 'IIIT'),
('Faculty of Technology & Engineering, MSU Baroda', 'Vadodara', 'State University', 'MSU'),
('Institute of Technology, Nirma University', 'Ahmedabad', 'Private', 'Nirma University'),
('Pandit Deendayal Energy University School of Technology', 'Gandhinagar', 'Private', 'PDEU'),
('Dharmsinh Desai University Engineering', 'Nadiad', 'State University', 'DDU'),
('CHARUSAT University Engineering', 'Anand', 'Private', 'CHARUSAT'),
('Marwadi University Engineering', 'Rajkot', 'Private', 'Marwadi Univ'),
('Ganpat University Engineering', 'Mehsana', 'Private', 'Ganpat Univ'),
('Parul University – Engineering Faculty', 'Vadodara', 'Private', 'Parul Univ'),
('Silver Oak University – Engineering', 'Ahmedabad', 'Private', 'Silver Oak Univ'),
('Ahmedabad University – Engineering', 'Ahmedabad', 'Private', 'Ahmedabad Univ'),
('Government Engineering College Gandhinagar', 'Gandhinagar', 'Government', 'GTU'),
('Government Engineering College Rajkot', 'Rajkot', 'Government', 'GTU'),
('Government Engineering College Bhavnagar', 'Bhavnagar', 'Government', 'GTU'),
('LD College of Engineering', 'Ahmedabad', 'Government', 'GTU'),
('Vishwakarma Government Engineering College', 'Ahmedabad', 'Government', 'GTU'),
('Birla Vishvakarma Mahavidyalaya', 'Vallabh Vidyanagar', 'Government', 'GTU'),
('Shantilal Shah Engineering College', 'Bhavnagar', 'Government', 'GTU'),
('C K Pithawala College of Engineering & Technology', 'Surat', 'Private', 'GTU'),
('Government Engineering College Valsad', 'Valsad', 'Government', 'GTU'),
('Government Engineering College Patan', 'Patan', 'Government', 'GTU'),
('Government Engineering College Surat', 'Surat', 'Government', 'GTU'),
('Government Engineering College Dahod', 'Dahod', 'Government', 'GTU'),
('Government Engineering College Mehsana', 'Mehsana', 'Government', 'GTU'),
('Government Engineering College Bharuch', 'Bharuch', 'Government', 'GTU'),
('Government Engineering College Godhra', 'Godhra', 'Government', 'GTU'),
('Ahmedabad Institute of Technology', 'Ahmedabad', 'Private', 'GTU'),
('Apollo Institute of Engineering & Technology', 'Ahmedabad', 'Private', 'GTU'),
('ITM Vocational University – Engineering', 'Vadodara', 'Private', 'ITM Voc Univ'),
('LJ Institute of Engineering & Technology', 'Ahmedabad', 'Private', 'GTU'),
('CSPIT Anand', 'Anand', 'Private', 'GTU');
